name: Copy App to EC2

on:
  push:
    branches:
      - master  # Replace with your branch name

jobs:
  copy-to-ec2:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy App to EC2
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client
          sudo scp -o StrictHostKeyChecking=no -r ./app ubuntu@54.87.60.6:/home/ubuntu

