name: Copy to Linux Server

on:
  push:
    branches:
      - master  # adjust the branch name if needed

jobs:
  copy-to-server:
    runs-on: ubuntu-latest  # GitHub Actions runner

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Copy to Server
      uses: appleboy/scp-action@master
      with:
        host: 34.201.92.1
        username: ubuntu
        key: ${{ secrets.SSH_PRIVATE_KEY }}
        source: "."
        target: "/home/ubuntu/"
